language: scala
sudo: false

# main scala version
scala:
  - 2.12.8

jdk:
  - openjdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.4.4 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.3

stages:
  - name: test
  - name: microsite
  - name: publishMicrosite
    if: (branch = master) OR (tag IS present)

jobs:
  include:
    - &lint
      stage: test
      name: "Lint"
      script: sbt ++TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Test for 2.12"
      script: sbt ++TRAVIS_SCALA_VERSION test
    - <<: *test
      scala: 2.11.12
      name: "Test for 2.11"
    - &scaladoc
      stage: microsite
      name: "Generate scaladoc"
      script: sbt ++$TRAVIS_SCALA_VERSION doc
    - &microsite
      stage: microsite
      name: "Generate microsite"
      script: sbt ++$TRAVIS_SCALA_VERSION microsite/makeMicrosite
    - &publishSite
      stage: publishMicrosite
      name: "Publish Microsite"
      script: sbt ++$TRAVIS_SCALA_VERSION microsite/publishMicrosite


