language: scala
sudo: false

# main scala version
scala:
  - 2.12.8

jdk:
  - openjdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle

stages:
  - name: test

jobs:
  include:
    - &lint
      stage: test
      name: "Lint"
      script: sbt ++TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Test for 2.12"
      script: sbt ++TRAVIS_SCALA_VERSION test:run
    - <<: *test
      scala: 2.11.12
      name: "Test for 2.11"
