name: Scala CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags: ['v*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
    - name: Cache scala dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.m2
          ~/.cache
        key: sbt-actors-cache
    - name: Lint code
      run: sbt check
    - name: Run tests
      run: sbt test
