name: Scala CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: ['adopt@1.8', 'adopt@1.11']
        scala: ['2.12.12', '2.13.3']
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: ${{ matrix.java }}
        scala-version: ${{ matrix.scala }}
    - name: Cache scala dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.m2
          ~/.cache
        key: sbt-actors-cache-${{ matrix.java }}-${{ matrix.scala }}
    - name: Lint code
      run: sbt check
    - name: Run tests
      run: sbt test
