name: Scala CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags: ['v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
    - name: Run compile
      run: sbt compile
    - name: Run scalafmt
      run: sbt check
    - name: Run tests
      run: sbt test
